//! Integration tests for `.cvpack` loading, using hostile fixtures generated by
//! `scripts/make-test-fixtures.py`.
//!
//! These exist because every pack shipped in this repository failed its own
//! manifest (declared `size_bytes: 0` and a zero checksum against a 30-byte
//! placeholder), and nothing in the test suite noticed. `dist_packs_are_loadable`
//! is the regression gate for exactly that.

use std::path::{Path, PathBuf};
use voice_pack::{LoadError, PackLimits, PackLoader, PackValidator};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn err_of(name: &str) -> LoadError {
    match PackLoader::new().load(&fixture(name)) {
        Ok(pack) => panic!(
            "expected {name} to be rejected, but it loaded (files: {:?})",
            pack.list_files()
        ),
        Err(err) => err,
    }
}

fn err_message(name: &str) -> String {
    err_of(name).to_string()
}

#[test]
fn ok_pack_loads_and_is_marked_placeholder() {
    let pack = PackLoader::new()
        .load(&fixture("ok.cvpack"))
        .expect("ok.cvpack must load; regenerate fixtures with scripts/make-test-fixtures.py");
    assert_eq!(pack.manifest.id, "fixture");
    assert!(pack.is_placeholder(), "fixture declares status=placeholder");
    assert_eq!(pack.file_size("model.onnx"), Some(36));
    assert!(!pack.list_files().is_empty());
}

#[test]
fn zip_bomb_is_rejected_before_inflation() {
    // 32 MB of zeros compresses to ~33 KB. A loader that decompresses first and
    // validates afterwards has already lost. The ratio check must fire on
    // central-directory metadata, before any inflate.
    let msg = err_message("zip_bomb.cvpack");
    assert!(
        msg.contains("compression ratio") || msg.contains("zip bomb") || msg.contains("limit"),
        "unexpected rejection reason: {msg}"
    );
}

#[test]
fn undeclared_entry_is_rejected() {
    let msg = err_message("undeclared_entry.cvpack");
    assert!(msg.contains("undeclared"), "unexpected rejection reason: {msg}");
}

#[test]
fn path_traversal_is_rejected() {
    let msg = err_message("path_traversal.cvpack");
    assert!(msg.contains("traversal"), "unexpected rejection reason: {msg}");
}

#[test]
fn executable_content_is_rejected() {
    let msg = err_message("executable.cvpack");
    assert!(
        msg.to_lowercase().contains("executable"),
        "unexpected rejection reason: {msg}"
    );
}

#[test]
fn tampered_bytes_fail_checksum() {
    let msg = err_message("tampered.cvpack");
    assert!(msg.contains("Checksum mismatch"), "unexpected: {msg}");
}

#[test]
fn truncated_file_fails_size_check() {
    let msg = err_message("truncated.cvpack");
    assert!(msg.contains("Size mismatch"), "unexpected: {msg}");
}

#[test]
fn zero_sized_declared_file_is_rejected() {
    // The original defect: manifests shipped `"size_bytes": 0` plus a zero hash.
    let msg = err_message("zero_size.cvpack");
    assert!(msg.contains("size 0"), "unexpected: {msg}");
}

#[test]
fn zero_hash_checksum_is_rejected() {
    let msg = err_message("zero_hash.cvpack");
    assert!(msg.contains("checksum"), "unexpected: {msg}");
}

#[test]
fn duplicate_manifest_entries_are_rejected() {
    let msg = err_message("duplicate.cvpack");
    assert!(msg.contains("Duplicate"), "unexpected: {msg}");
}

#[test]
fn real_pack_without_provenance_is_rejected() {
    // VOICE_INV_008: provenance is mandatory for a pack that claims to be real.
    let msg = err_message("real_no_provenance.cvpack");
    assert!(msg.contains("provenance"), "unexpected: {msg}");
}

#[test]
fn wrong_schema_version_is_rejected() {
    let msg = err_message("bad_schema.cvpack");
    assert!(
        msg.contains("schema version") || msg.contains("schema_version"),
        "unexpected: {msg}"
    );
}

#[test]
fn not_a_zip_is_rejected() {
    assert!(matches!(err_of("not_a_zip.cvpack"), LoadError::InvalidZip(_)));
}

#[test]
fn missing_file_reports_file_not_found() {
    let err = PackLoader::new().load(&fixture("does_not_exist.cvpack"));
    assert!(
        matches!(err, Err(LoadError::FileNotFound(_))),
        "got {err:?}"
    );
}

#[test]
fn embedded_limits_are_stricter_than_desktop() {
    // 200 MB declared single file: within the desktop budget, over the Pi budget.
    let path = fixture("oversize.cvpack");
    let desktop = PackLoader::new().load(&path);
    let embedded = PackLoader::with_validator(PackValidator::with_limits(PackLimits::embedded()))
        .load(&path);

    assert!(
        desktop.is_err(),
        "oversize fixture declares 200 MB but stores 1 KB, so size verification must fail"
    );
    let embedded_err = embedded.unwrap_err().to_string();
    assert!(
        embedded_err.contains("per-file limit") || embedded_err.contains("Size mismatch"),
        "unexpected: {embedded_err}"
    );

    assert!(PackLimits::tiny().max_file_bytes < PackLimits::embedded().max_file_bytes);
    assert!(PackLimits::embedded().max_file_bytes < PackLimits::default().max_file_bytes);
}

#[test]
fn limits_profiles_are_sane() {
    let tiny = PackLimits::tiny();
    let embedded = PackLimits::embedded();
    let desktop = PackLimits::default();
    assert!(tiny.max_total_bytes > 0);
    assert!(embedded.max_file_count > 0);
    assert!(desktop.max_compression_ratio > 1.0);
    assert!(embedded.max_file_count < desktop.max_file_count);
}

/// THE regression gate: every pack in `voice-packs/dist/` must load.
///
/// All three shipped packs previously failed validation, yet the phase document
/// reported "Three voices load successfully ✅" because CI only asserted that the
/// files *existed* (`test -f voice-packs/dist/tara.cvpack`).
#[test]
fn dist_packs_are_loadable() {
    let dist = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../voice-packs/dist");
    assert!(
        dist.is_dir(),
        "{} does not exist — voice-packs/dist is a tracked deliverable",
        dist.display()
    );

    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dist)
        .expect("read voice-packs/dist")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("cvpack"))
        .collect();
    paths.sort();

    let mut checked = 0usize;
    for path in paths {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        match PackLoader::new().load(&path) {
            Ok(pack) => {
                assert!(!pack.manifest.files.is_empty(), "{name}: no files declared");
                // Placeholder packs are legal scaffolding, but they must declare it.
                // A tiny model without `status: "placeholder"` would be mistaken for a
                // usable voice — which is precisely how this repo shipped.
                let model_len = pack.get_file("model.onnx").map(|b| b.len()).unwrap_or(0);
                if model_len < 1_000_000 {
                    assert!(
                        pack.is_placeholder(),
                        "{name}: model.onnx is only {model_len} bytes but status is not \
                         \"placeholder\" — this pack would be mistaken for a usable voice"
                    );
                }
                checked += 1;
            }
            Err(err) => panic!(
                "{name} failed validation: {err}\n\
                 Rebuild with: python3 scripts/build-voice-packs.py build"
            ),
        }
    }

    assert_eq!(checked, 3, "expected tara, kashi and bobo packs to load");
}
